# 1. Data Audit: `customers` table

An initial data profiling was performed on the olist_customer_dataset.csv file using Pandas to define the architecture for the PostgreSQL database.

## Technical Findings:
* **Data Volume:** 99,441 records.
* **Column Integrity:** Identified **5 columns** with 100% non-null values.

### Cardinality Analysis:
* **`customer_id`:** Contains 99,441 unique values, confirming its suitability as the **Primary Key (PK)**.
* **`customer_unique_id`:** Contains 96,096 unique values, indicating the presence of returning customers (repeat purchases).

In [2]:
import pandas as pd

df_customers = pd.read_csv('../data/olist_customers_dataset.csv')

data_quality = pd.DataFrame({
    'Type': df_customers.dtypes,
    'Non-Nulls': df_customers.count(),
    'Nulls': df_customers.isnull().sum(),
    'Unique Values': df_customers.nunique(),
    'Duplicated': len(df_customers) - df_customers.nunique()
})

data_quality

                            Type  Non-Nulls  Nulls  Unique Values  Duplicated
customer_id               object      99441      0          99441           0
customer_unique_id        object      99441      0          96096        3345
customer_zip_code_prefix   int64      99441      0          14994       84447
customer_city             object      99441      0           4119       95322
customer_state            object      99441      0             27       99414

## 1.2. Data Type & Storage Definition

Basado en el análisis de longitudes y naturaleza de los datos, se establecen las siguientes reglas de negocio para SQL:

* **IIdentifiers (`customer_id`, `unique_id`):** Fixed length of 32 characters. Decision: Use `CHAR(32)` o `VARCHAR(32)` for storage efficiency.
* **`customer_city`:** Range between 3 and 35 characters. Decision: `VARCHAR(100)`.
* **`customer_state`:** Fixed length of 2 characters. Technical Decision: `CHAR(2)`.
* **`customer_zip_code_prefix`:** Detected as `int64`. Recommendation: `VARCHAR(5)` or `INTEGER` (considering leading zeros).

In [3]:
##############################################################################################################

# SELECT THE OBJETS DATA COLUMNS TO DECIDE WHAT DATA TYPE TO USE

##############################################################################################################

df_analisys = df_customers.select_dtypes(include=['object'])\
                        .apply(lambda x: x.str.len())\
                        .agg(['min', 'max']).T\
                        .reset_index()

df_analisys.columns = ['Column','Min Lenght', 'Max Lenght']

df_analisys

               Column  Min Lenght  Max Lenght
0         customer_id          32          32
1  customer_unique_id          32          32
2       customer_city           3          32
3      customer_state           2           2